In [1]:
import math
import pandas as pd
import numpy as np
import sklearn
import scipy.stats as stats

## Problem-1

In [2]:
def calculate_confidence_interval(x):
    # Sample size
    n = 200

    p_hat = x / n

    confidence_level = 0.90

    # Calculate the standard error
    standard_error = math.sqrt((p_hat * (1 - p_hat)) / n)

    # Find the critical value for the confidence interval
    z_critical = stats.norm.ppf((1 + confidence_level) / 2)

    # Calculate the margin of error
    margin_of_error = z_critical * standard_error

    # Calculate the confidence interval
    lower_bound = p_hat - margin_of_error
    upper_bound = p_hat + margin_of_error

    return round(lower_bound, 5), round(upper_bound, 5), round(margin_of_error, 5)

x = int(input("Enter the number of highly satisfied customers: "))

lower_bound, upper_bound, margin_of_error = calculate_confidence_interval(x)

print(f"Confidence Interval: [{lower_bound}, {upper_bound}]")
print(f"Margin of Error: {margin_of_error}")

Enter the number of highly satisfied customers: 99
Confidence Interval: [0.43685, 0.55315]
Margin of Error: 0.05815

## Problem-2

In [3]:
def probability_more_than_x(speed_x, mean, std_dev):
    z_score = (speed_x - mean) / std_dev

    probability = 1 - stats.norm.cdf(z_score)

    return round(probability, 4)

mean_speed = 75  # Mean speed in km/hr
std_dev_speed = 15  # Standard deviation in km/hr

speed_x = float(input("Enter the speed (X) in km/hr: "))

result_probability = probability_more_than_x(speed_x, mean_speed, std_dev_speed)

print(f"The probability that a car is traveling at more than {speed_x} km/hr is: {result_probability}")

Enter the speed (X) in km/hr: 88
The probability that a car is traveling at more than 88.0 km/hr is: 0.1931

In [4]:
kerela_df=pd.read_csv(r"C:\Users\HP\Documents\ALL EDUREKA PRACTICE CODES\All Data Files\kerala.csv")

In [5]:
kerela_df

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,KERALA,2014,4.6,10.3,17.9,95.7,251.0,454.4,677.8,733.9,298.8,355.5,99.5,47.2,3046.4,YES
114,KERALA,2015,3.1,5.8,50.1,214.1,201.8,563.6,406.0,252.2,292.9,308.1,223.6,79.4,2600.6,NO
115,KERALA,2016,2.4,3.8,35.9,143.0,186.4,522.2,412.3,325.5,173.2,225.9,125.4,23.6,2176.6,NO
116,KERALA,2017,1.9,6.8,8.9,43.6,173.5,498.5,319.6,531.8,209.5,192.4,92.5,38.1,2117.1,NO
117,KERALA,2018,29.1,52.1,48.6,116.4,183.8,625.4,1048.5,1398.9,423.6,356.1,125.4,65.1,4473.0,YES

In [6]:
kerela_df.head(20)

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO
5,KERALA,1906,26.7,7.4,9.9,59.4,160.8,414.9,954.2,442.8,131.2,251.7,163.1,86.0,2708.0,NO
6,KERALA,1907,18.8,4.8,55.7,170.8,101.4,770.9,760.4,981.5,225.0,309.7,219.1,52.8,3671.1,YES
7,KERALA,1908,8.0,20.8,38.2,102.9,142.6,592.6,902.2,352.9,175.9,253.3,47.9,11.0,2648.3,NO
8,KERALA,1909,54.1,11.8,61.3,93.8,473.2,704.7,782.3,258.0,195.4,212.1,171.1,32.3,3050.2,YES
9,KERALA,1910,2.7,25.7,23.3,124.5,148.8,680.0,484.1,473.8,248.6,356.6,280.4,0.1,2848.6,NO
10,KERALA,1911,3.0,4.3,18.2,51.0,180.6,990.0,705.3,178.6,60.2,302.3,145.7,87.6,2726.7,NO
11,KERALA,1912,1.9,15.0,11.2,122.7,217.3,948.2,833.6,534.4,136.8,469.5,138.7,22.0,3451.3,YES
12,KERALA,1913,3.1,5.2,20.7,75.7,198.8,541.7,763.2,247.2,176.9,422.5,109.9,45.8,2610.8,NO
13,KERALA,1914,0.7,6.8,18.1,32.7,164.2,565.3,857.7,402.2,241.0,374.4,100.9,135.2,2899.1,NO
14,KERALA,1915,16.9,23.5,42.7,106.0,154.5,696.1,775.6,298.8,396.6,196.6,302.5,14.9,3024.5,YES
15,KERALA,1916,0.0,7.8,22.0,82.4,199.0,920.2,513.9,396.9,339.3,320.7,134.3,8.9,2945.3,YES
16,KERALA,1917,2.9,47.6,79.4,38.1,122.9,703.7,342.7,335.1,470.3,264.1,256.4,41.6,2704.8,NO
17,KERALA,1918,42.9,5.0,32.8,51.3,683.0,464.3,167.5,376.0,96.4,233.2,295.4,54.1,2501.9,NO
18,KERALA,1919,43.0,6.1,33.9,65.9,247.0,636.8,648.0,484.2,255.9,249.2,280.1,53.0,3003.3,YES
19,KERALA,1920,35.2,5.5,24.1,172.0,87.7,964.3,940.8,235.0,178.0,350.1,302.3,8.2,3303.1,YES

In [7]:
kerela_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SUBDIVISION       118 non-null    object
 1   YEAR              118 non-null    int64
 2   JAN               118 non-null    float64
 3   FEB               118 non-null    float64
 4   MAR               118 non-null    float64
 5   APR               118 non-null    float64
 6   MAY               118 non-null    float64
 7   JUN               118 non-null    float64
 8   JUL               118 non-null    float64
 9   AUG               118 non-null    float64
 10  SEP               118 non-null    float64
 11  OCT               118 non-null    float64
 12  NOV               118 non-null    float64
 13  DEC               118 non-null    float64
 14   ANNUAL RAINFALL  118 non-null    float64
 15  FLOODS            118 non-null    object
dtypes: float64(13), int64(1), object(2)
memory usage: 14.9+ KB

In [8]:
kerela_df.describe()

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL
count,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000
mean,1959.500000,12.218644,15.633898,36.670339,110.330508,228.644915,651.617797,698.220339,430.369492,246.207627,293.207627,162.311017,40.009322,2925.405085
std,34.207699,15.473766,16.406290,30.063862,44.633452,147.548778,186.181363,228.988966,181.980463,121.901131,93.705253,83.200485,36.676330,452.169407
min,1901.000000,0.000000,0.000000,0.100000,13.100000,53.400000,196.800000,167.500000,178.600000,41.300000,68.500000,31.500000,0.100000,2068.800000
25%,1930.250000,2.175000,4.700000,18.100000,74.350000,125.050000,535.550000,533.200000,316.725000,155.425000,222.125000,93.025000,10.350000,2613.525000
50%,1959.500000,5.800000,8.350000,28.400000,110.400000,184.600000,625.600000,691.650000,386.250000,223.550000,284.300000,152.450000,31.100000,2934.300000
75%,1988.750000,18.175000,21.400000,49.825000,136.450000,264.875000,786.975000,832.425000,500.100000,334.500000,355.150000,218.325000,54.025000,3170.400000
max,2018.000000,83.500000,79.000000,217.200000,238.000000,738.800000,1098.200000,1526.500000,1398.900000,526.700000,567.900000,365.600000,202.300000,4473.000000

In [9]:
result_df = pd.DataFrame(columns=["YEAR", "JUN_GT_500", "JUL_GT_500", "FLOODS"])

for index, row in kerela_df.iterrows():
    year = row['YEAR']
    jun_gt_500 = row['JUN'] > 500
    jul_gt_500 = row['JUL'] > 500
    floods = jun_gt_500 or jul_gt_500

    result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result_df = result_df.append({"YEAR": year, "JUN_GT_500": jun_gt_500, "JUL_GT_500": jul_gt_500, "FLOODS": floods}, ignore_index=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22436\3977658568.py:9: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.

In [10]:
prob_A_and_B = result_df[(result_df['JUN_GT_500'] == True) & (result_df['FLOODS'] == True)].shape[0] / result_df.shape[0]

prob_B = result_df[result_df['JUN_GT_500'] == True].shape[0] / result_df.shape[0]

prob_A_given_B = prob_A_and_B / prob_B

print(f"Probability of floods given it rained more than 500 mm in June (P(A|B)): {prob_A_given_B:.2f}")

Probability of floods given it rained more than 500 mm in June (P(A|B)): 1.00

In [11]:
prob_A_and_B = result_df[(result_df['JUN_GT_500'] == True) & (result_df['FLOODS'] == True)].shape[0] / result_df.shape[0]

prob_A = result_df[result_df['FLOODS'] == True].shape[0] / result_df.shape[0]

prob_B_given_A = prob_A_and_B / prob_A

print(f"Probability of raining more than 500 mm in June given it flooded that year (P(B|A)): {prob_B_given_A:.2f}")

Probability of raining more than 500 mm in June given it flooded that year (P(B|A)): 0.81

In [12]:
prob_A_and_C = result_df[(result_df['JUL_GT_500'] == True) & (result_df['FLOODS'] == True)].shape[0] / result_df.shape[0]

prob_C = result_df[result_df['JUL_GT_500'] == True].shape[0] / result_df.shape[0]

prob_A_given_C = prob_A_and_C / prob_C

print(f"Probability of floods given it rained more than 500 mm in July (P(A|C)): {prob_A_given_C:.2f}")

Probability of floods given it rained more than 500 mm in July (P(A|C)): 1.00

In [13]:
prob_A_and_B = result_df[(result_df['JUL_GT_500'] == True) & (result_df['FLOODS'] == True)].shape[0] / result_df.shape[0]

prob_A = result_df[result_df['FLOODS'] == True].shape[0] / result_df.shape[0]

prob_B_given_A = prob_A_and_B / prob_A

print(f"Probability of raining more than 500 mm in July given it flooded that year (P(B|A)): {prob_B_given_A:.2f}")

Probability of raining more than 500 mm in July given it flooded that year (P(B|A)): 0.83

In [19]:
from sklearn.datasets import load_wine

data = load_wine()

wine_df = pd.DataFrame(data.data, columns=data.feature_names)
wine_df['target'] = data.target

In [20]:
wine_df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [26]:
from sklearn.model_selection import train_test_split
random_state = 100
sample_size = 50

_, sample_df, _, _ = train_test_split(wine_df, wine_df['target'], test_size=sample_size / len(wine_df), random_state=random_state)

In [27]:
sample_mean = sample_df['alcohol'].mean()
sample_std = sample_df['alcohol'].std()

confidence_level = 0.95

z_critical = stats.norm.ppf(confidence_level + (1 - confidence_level) / 2)

margin_of_error = z_critical * (sample_std / (sample_size ** 0.5))

confidence_interval = (sample_mean - margin_of_error, sample_mean + margin_of_error)

print(f"Z-critical value: {z_critical:.3f}")
print(f"Margin of Error: {margin_of_error:.3f}")
print(f"Confidence Interval: {confidence_interval}")

Z-critical value: 1.960
Margin of Error: 0.213
Confidence Interval: (12.76054046553653, 13.186659534463468)

# END